### ISSUE TITLE
Code fix required to correct the Corporate Account owners for the AA feed

### ISSUE THREAD

**Issue by Sir-Rancelot** [Sir-Rancelot/github-slideshow#2]

**Comment by Paul-Gallagher** [comment]
See [ICW-6405](https://jira.baplc.com/browse/ICW-6405)

**Comment by Sir-Rancelot** [comment]
oh that is cool - I like it

**Comment by Paul-Gallagher** [comment]
- [x]  Welcome to 2021 
- [ ]  Get others to use it
- [ ]  Party on

**Comment by Sir-Rancelot** [comment]
I will add a profile pic tomorrow
just trying to think of something fun to add

**Comment by Paul-Gallagher** [comment]
Collecting up Tony's chat replies into Jira now ... needs V or D to review I guess but otherwise, guess it can go straight away on a BAU / bug fix ticket

**Comment by Sir-Rancelot** [comment]
Live on 16 Sept - great work buddy.

Plus I added a profile picture

**Comment by Sir-Rancelot** [comment]
closing this issue as work is completed.
